import type { ProfilePageReferenceData } from "@/lib/profile-page-types"

const IMG = {
  strat: "/profile/items/strat-62.jpg",
  lesPaul: "/profile/items/les-paul-59.jpg",
  tele: "/profile/items/telecaster.jpg",
  es335: "/profile/items/es-335.jpg",
  twin: "/profile/items/fender-twin.jpg",
  plexi: "/profile/items/marshall-plexi.jpg",
  ac30: "/profile/items/vox-ac30.jpg",
  deluxe: "/profile/items/fender-deluxe.jpg",
  klon: "/profile/items/klon-centaur.jpg",
  delay: "/profile/items/delay-pedal.jpg",
  tuner: "/profile/items/tuner-pedal.jpg",
  muff: "/profile/items/big-muff.jpg",
  jcm800: "/profile/items/jcm800.jpg",
  dumble: "/profile/items/dumble.jpg",
}

export const profilePageData: ProfilePageReferenceData = {
  profile: {
    username: "guitar_collector",
    avatarLabel: "GC",
    avatarUrl: "/profile/avatar-guitar-collector.jpg",
    location: "Nashville, TN",
    memberSince: "2023-01-15T00:00:00.000Z",
    bio: "Vintage guitar enthusiast and tube amp collector. Always looking for pre-CBS Fenders, old Marshalls, and original PAF pickups.",
    stats: {
      totalItems: 27,
      totalCollections: 3,
      totalTrades: 12,
    },
    verification: {
      email: true,
      phone: true,
      id: false,
    },
    linkedAccounts: [
      { platform: "reddit", username: "guitar_collector_92", verified: true },
      { platform: "ebay", username: "vintageguitars_nash", verified: false },
      { platform: "reverb", username: "NashvilleVintage", verified: false },
    ],
  },
  collections: [
    {
      id: "collection-1",
      name: "Vintage Guitars",
      description: "Pre-1970 American classics",
      visibility: "public",
      itemCount: 8,
      totalValue: 185000,
      isWishlist: false,
      previewLabels: ["Strat", "Burst", "Tele", "335"],
      previewImages: [IMG.strat, IMG.lesPaul, IMG.tele, IMG.es335],
    },
    {
      id: "collection-2",
      name: "Tube Amplifiers",
      description: "Fender, Marshall, Vox",
      visibility: "public",
      itemCount: 5,
      totalValue: 24500,
      isWishlist: false,
      previewLabels: ["Twin", "Plexi", "AC30", "Deluxe"],
      previewImages: [IMG.twin, IMG.plexi, IMG.ac30, IMG.deluxe],
    },
    {
      id: "collection-3",
      name: "Pedal Board",
      description: "Current touring setup",
      visibility: "unlisted",
      itemCount: 12,
      totalValue: 4800,
      isWishlist: false,
      previewLabels: ["Klon", "Time", "TU", "Muff"],
      previewImages: [IMG.klon, IMG.delay, IMG.tuner, IMG.muff],
    },
  ],
  forSaleItems: [
    {
      id: "sale-1",
      title: "1962 Fender Stratocaster",
      subtitle: "Sunburst, all original",
      imageLabel: "Strat",
      imageUrl: IMG.strat,
      price: 48000,
      forSale: true,
      forTrade: true,
      listedAt: "2024-01-10T00:00:00.000Z",
    },
    {
      id: "sale-2",
      title: "Marshall JCM800 2203",
      subtitle: "1982, fully serviced",
      imageLabel: "JCM800",
      imageUrl: IMG.jcm800,
      price: 2800,
      forSale: true,
      forTrade: false,
      listedAt: "2024-01-08T00:00:00.000Z",
    },
    {
      id: "sale-3",
      title: "Klon Centaur Gold",
      subtitle: "Original, with box",
      imageLabel: "Klon",
      imageUrl: IMG.klon,
      price: 4500,
      forSale: true,
      forTrade: true,
      listedAt: "2024-01-05T00:00:00.000Z",
    },
    {
      id: "sale-4",
      title: "Vox AC30 Top Boost",
      subtitle: "Early 70s, serviced",
      imageLabel: "AC30",
      imageUrl: IMG.ac30,
      price: 3200,
      forSale: true,
      forTrade: false,
      listedAt: "2023-12-28T00:00:00.000Z",
    },
    {
      id: "sale-5",
      title: "EHX Big Muff Pi (v3)",
      subtitle: "Ram's Head era, tested",
      imageLabel: "Muff",
      imageUrl: IMG.muff,
      price: 420,
      forSale: true,
      forTrade: true,
      listedAt: "2023-12-20T00:00:00.000Z",
    },
  ],
  tradeInterests: [
    {
      id: "trade-1",
      name: "Pre-CBS Fender Electrics",
      description: "Open to trades for any original, unmodified pre-1965 Fender guitar.",
      addedAt: "2024-01-14T00:00:00.000Z",
      criteria: [
        { label: "Category", value: "Electric Guitars" },
        { label: "Brand", value: "Fender" },
        { label: "Era", value: "1954 - 1964" },
        { label: "Condition", value: "All original" },
        { label: "Budget", value: "$15k - $60k" },
        { label: "Region", value: "US domestic" },
      ],
    },
    {
      id: "trade-2",
      name: "Vintage British Tube Amps",
      description: "Looking for plexi-era heads and early AC30 combos. Serviced preferred.",
      addedAt: "2024-01-09T00:00:00.000Z",
      criteria: [
        { label: "Category", value: "Tube Amplifiers" },
        { label: "Brand", value: "Marshall, Vox, Hiwatt" },
        { label: "Era", value: "1965 - 1975" },
        { label: "Condition", value: "Working, serviced" },
        { label: "Budget", value: "$2.5k - $12k" },
      ],
    },
    {
      id: "trade-3",
      name: "Boutique Overdrive Pedals",
      description: "Trades welcome for low-production gold-era Klon-style drives.",
      addedAt: "2023-12-30T00:00:00.000Z",
      criteria: [
        { label: "Category", value: "Effects Pedals" },
        { label: "Type", value: "Overdrive / Transparent" },
        { label: "Brand", value: "Klon, Analog.Man, Vemuram" },
        { label: "Condition", value: "Boxed, clean" },
        { label: "Budget", value: "Under $5k" },
      ],
    },
  ],
  lookingForItems: [
    {
      id: "wish-1",
      title: "1959 Gibson Les Paul Standard",
      subtitle: "Sunburst, original PAFs",
      imageLabel: "Burst",
      imageUrl: IMG.lesPaul,
      addedAt: "2024-01-12T00:00:00.000Z",
    },
    {
      id: "wish-2",
      title: "Dumble Overdrive Special",
      subtitle: "Any year, working condition",
      imageLabel: "Dumble",
      imageUrl: IMG.dumble,
      addedAt: "2024-01-10T00:00:00.000Z",
    },
    {
      id: "wish-3",
      title: "Original Klon Centaur",
      subtitle: "Silver or gold",
      imageLabel: "Klon",
      imageUrl: IMG.klon,
      addedAt: "2024-01-08T00:00:00.000Z",
    },
    {
      id: "wish-4",
      title: "1963 Fender Stratocaster",
      subtitle: "Pre-CBS, original finish",
      imageLabel: "63 Strat",
      imageUrl: IMG.strat,
      addedAt: "2024-01-05T00:00:00.000Z",
    },
    {
      id: "wish-5",
      title: "Gibson ES-335 Dot",
      subtitle: "Pre-1965, cherry preferred",
      imageLabel: "335",
      imageUrl: IMG.es335,
      addedAt: "2023-12-30T00:00:00.000Z",
    },
    {
      id: "wish-6",
      title: "Blackface Fender Deluxe Reverb",
      subtitle: "1964 - 1967, unmodified",
      imageLabel: "Deluxe",
      imageUrl: IMG.deluxe,
      addedAt: "2023-12-18T00:00:00.000Z",
    },
  ],
  activity: [
    {
      id: "activity-1",
      type: "listing",
      description: "Listed 1962 Fender Stratocaster for sale",
      timestamp: "2024-01-10T14:30:00.000Z",
    },
    {
      id: "activity-2",
      type: "trade",
      description: "Completed trade with @vintagegearnyc",
      timestamp: "2024-01-08T10:15:00.000Z",
    },
    {
      id: "activity-3",
      type: "collection",
      description: "Added Marshall JCM800 to Tube Amplifiers collection",
      timestamp: "2024-01-07T16:45:00.000Z",
    },
    {
      id: "activity-4",
      type: "offer",
      description: "Made an offer on Gibson ES-335",
      timestamp: "2024-01-05T09:20:00.000Z",
    },
    {
      id: "activity-5",
      type: "follow",
      description: "Started following @tubescreamer_fan",
      timestamp: "2024-01-03T11:00:00.000Z",
    },
    {
      id: "activity-6",
      type: "listing",
      description: "Listed Vox AC30 Top Boost for sale",
      timestamp: "2023-12-28T13:10:00.000Z",
    },
    {
      id: "activity-7",
      type: "collection",
      description: "Created collection \"Pedal Board\"",
      timestamp: "2023-12-22T17:05:00.000Z",
    },
  ],
}
