import type { Conversation, Message } from "@/lib/inbox-types"
import { CURRENT_USER_ID } from "@/lib/inbox-types"

const now = Date.now()

const img = {
  strat: "https://images.unsplash.com/photo-1564186763535-ebb21ef5277f?w=400&h=300&fit=crop",
  lesPaul: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=400&h=300&fit=crop",
  jcm800: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
  jazzmaster: "https://images.unsplash.com/photo-1525201548942-d8732f6617a0?w=400&h=300&fit=crop",
}

const avatars = {
  vintagegearnyc: "https://i.pravatar.cc/150?u=vintagegearnyc",
  tubescreamerfan: "https://i.pravatar.cc/150?u=tubescreamerfan",
  marshallmaven: "https://i.pravatar.cc/150?u=marshallmaven",
  tonechaserla: "https://i.pravatar.cc/150?u=tonechaserla",
}

export const demoConversations: Conversation[] = [
  {
    id: "conv-1",
    participant: {
      id: "user-1",
      username: "vintagegearnyc",
      avatar_url: avatars.vintagegearnyc,
      location: "New York, NY",
      joined_at: "2022-03-15T00:00:00.000Z",
      stats: {
        items: 47,
        collections: 8,
        transactions: 23,
        response_rate: 95,
        avg_response_time: "< 1 hour",
      },
      feedback_score: 98,
      verification: { email: true, phone: true, id: true },
      linked_accounts: [
        { platform: "reverb", username: "VintageGearNYC", verified: true },
        { platform: "ebay", username: "vintagegear_nyc", verified: true },
      ],
      bio: "Collector of vintage guitars and amps, focused on pre-CBS Fender and late-60s Marshall pieces.",
    },
    subject_type: "listing",
    subject: {
      id: "listing-1",
      title: "1965 Fender Stratocaster",
      subtitle: "Pre-CBS, original pickups",
      image: img.strat,
      price: 18500,
    },
    last_message: {
      content: "Would you consider a trade plus cash?",
      created_at: new Date(now - 1000 * 60 * 32).toISOString(),
      sender_id: "user-1",
    },
    active_offer: {
      id: "offer-1",
      conversation_id: "conv-1",
      sender_id: "user-1",
      status: "pending",
      their_items: [
        {
          id: "their-1",
          title: "1959 Gibson Les Paul",
          subtitle: "Sunburst, PAF pickups",
          image: img.lesPaul,
          price: 15000,
        },
      ],
      your_items: [
        {
          id: "listing-1",
          title: "1965 Fender Stratocaster",
          subtitle: "Pre-CBS, original pickups",
          image: img.strat,
          price: 18500,
        },
      ],
      cash_adjustment: 4000,
      expires_at: new Date(now + 1000 * 60 * 60 * 36).toISOString(),
      created_at: new Date(now - 1000 * 60 * 60).toISOString(),
    },
    unread_count: 2,
    created_at: new Date(now - 1000 * 60 * 60 * 24 * 4).toISOString(),
    updated_at: new Date(now - 1000 * 60 * 32).toISOString(),
  },
  {
    id: "conv-2",
    participant: {
      id: "user-2",
      username: "tubescreamerfan",
      avatar_url: avatars.tubescreamerfan,
      location: "Austin, TX",
      joined_at: "2023-06-20T00:00:00.000Z",
      stats: {
        items: 12,
        collections: 3,
        transactions: 5,
        response_rate: 88,
        avg_response_time: "2-3 hours",
      },
      feedback_score: 100,
      verification: { email: true, phone: false, id: false },
      linked_accounts: [{ platform: "reddit", username: "tubescreamerfan", verified: true }],
      bio: "Pedal collector and tone chaser. Always looking for vintage Tube Screamers and rare fuzzes.",
    },
    subject_type: "direct",
    last_message: {
      content: "Hey, your collection is incredible. Would love to chat about those old fuzz faces.",
      created_at: new Date(now - 1000 * 60 * 60 * 3).toISOString(),
      sender_id: "user-2",
    },
    unread_count: 1,
    created_at: new Date(now - 1000 * 60 * 60 * 5).toISOString(),
    updated_at: new Date(now - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: "conv-3",
    participant: {
      id: "user-3",
      username: "marshallmaven",
      avatar_url: avatars.marshallmaven,
      location: "Nashville, TN",
      joined_at: "2021-01-10T00:00:00.000Z",
      stats: {
        items: 89,
        collections: 15,
        transactions: 67,
        response_rate: 99,
        avg_response_time: "< 30 mins",
      },
      feedback_score: 100,
      verification: { email: true, phone: true, id: true },
      linked_accounts: [
        { platform: "reverb", username: "MarshallMaven", verified: true },
        { platform: "ebay", username: "marshall_maven_amps", verified: true },
        { platform: "facebook", username: "marshall.maven", verified: true },
      ],
      bio: "Thirty years in the vintage amp world. If it glows, I probably know it.",
    },
    subject_type: "listing",
    subject: {
      id: "listing-2",
      title: "Marshall JCM800 2203",
      subtitle: "1982 vertical input",
      image: img.jcm800,
      price: 2800,
    },
    last_message: {
      content: "Thanks for the purchase. I will ship it tomorrow morning.",
      created_at: new Date(now - 1000 * 60 * 60 * 26).toISOString(),
      sender_id: "user-3",
    },
    unread_count: 0,
    created_at: new Date(now - 1000 * 60 * 60 * 24 * 7).toISOString(),
    updated_at: new Date(now - 1000 * 60 * 60 * 26).toISOString(),
  },
  {
    id: "conv-4",
    participant: {
      id: "user-4",
      username: "tonechaserla",
      avatar_url: avatars.tonechaserla,
      location: "Los Angeles, CA",
      joined_at: "2022-08-10T00:00:00.000Z",
      stats: {
        items: 31,
        collections: 5,
        transactions: 18,
        response_rate: 92,
        avg_response_time: "1-2 hours",
      },
      feedback_score: 96,
      verification: { email: true, phone: true, id: false },
      linked_accounts: [{ platform: "reverb", username: "ToneChaserLA", verified: true }],
      bio: "Session guitarist buying and selling fast. Cash buyer, quick decisions, clean deals.",
    },
    subject_type: "listing",
    subject: {
      id: "listing-3",
      title: "1962 Fender Jazzmaster",
      subtitle: "Olympic White, matching headstock",
      image: img.jazzmaster,
      price: 12500,
    },
    last_message: {
      content: "I can do $11,000 cash today if that gets it done.",
      created_at: new Date(now - 1000 * 60 * 48).toISOString(),
      sender_id: "user-4",
    },
    active_offer: {
      id: "offer-2",
      conversation_id: "conv-4",
      sender_id: "user-4",
      status: "pending",
      their_items: [],
      your_items: [
        {
          id: "listing-3",
          title: "1962 Fender Jazzmaster",
          subtitle: "Olympic White, matching headstock",
          image: img.jazzmaster,
          price: 12500,
        },
      ],
      cash_adjustment: 11000,
      expires_at: new Date(now + 1000 * 60 * 60 * 24).toISOString(),
      created_at: new Date(now - 1000 * 60 * 50).toISOString(),
    },
    unread_count: 1,
    created_at: new Date(now - 1000 * 60 * 60 * 6).toISOString(),
    updated_at: new Date(now - 1000 * 60 * 48).toISOString(),
  },
]

export const demoMessages: Record<string, Message[]> = {
  "conv-1": [
    {
      id: "msg-1",
      conversation_id: "conv-1",
      sender_id: "user-1",
      content: "Hi, I am interested in your 1965 Stratocaster. Beautiful guitar.",
      created_at: new Date(now - 1000 * 60 * 60 * 3).toISOString(),
      read: true,
      type: "text",
    },
    {
      id: "msg-2",
      conversation_id: "conv-1",
      sender_id: CURRENT_USER_ID,
      content: "Thanks. It has been in my collection for five years. What would you like to know?",
      created_at: new Date(now - 1000 * 60 * 60 * 2.5).toISOString(),
      read: true,
      type: "text",
    },
    {
      id: "msg-3",
      conversation_id: "conv-1",
      sender_id: "user-1",
      content: "I have a 1959 Les Paul I would be willing to trade. Would you consider a trade plus cash?",
      created_at: new Date(now - 1000 * 60 * 60 * 2).toISOString(),
      read: true,
      type: "text",
    },
    {
      id: "msg-4",
      conversation_id: "conv-1",
      sender_id: "user-1",
      content: "",
      created_at: new Date(now - 1000 * 60 * 60).toISOString(),
      read: false,
      type: "offer",
      offer_id: "offer-1",
    },
    {
      id: "msg-5",
      conversation_id: "conv-1",
      sender_id: "user-1",
      content: "Let me know what you think of the offer.",
      created_at: new Date(now - 1000 * 60 * 32).toISOString(),
      read: false,
      type: "text",
    },
  ],
  "conv-2": [
    {
      id: "msg-6",
      conversation_id: "conv-2",
      sender_id: "user-2",
      content: "Hey, your collection is incredible. Would love to chat about those old fuzz faces.",
      created_at: new Date(now - 1000 * 60 * 60 * 3).toISOString(),
      read: false,
      type: "text",
    },
  ],
  "conv-3": [
    {
      id: "msg-7",
      conversation_id: "conv-3",
      sender_id: CURRENT_USER_ID,
      content: "I would like to buy the JCM800. Is it still available?",
      created_at: new Date(now - 1000 * 60 * 60 * 48).toISOString(),
      read: true,
      type: "text",
    },
    {
      id: "msg-8",
      conversation_id: "conv-3",
      sender_id: "user-3",
      content: "Yes. It is all yours. I will send you payment details.",
      created_at: new Date(now - 1000 * 60 * 60 * 40).toISOString(),
      read: true,
      type: "text",
    },
    {
      id: "msg-9",
      conversation_id: "conv-3",
      sender_id: "user-3",
      content: "Thanks for the purchase. I will ship it tomorrow morning.",
      created_at: new Date(now - 1000 * 60 * 60 * 26).toISOString(),
      read: true,
      type: "text",
    },
  ],
  "conv-4": [
    {
      id: "msg-10",
      conversation_id: "conv-4",
      sender_id: "user-4",
      content: "Hey, I have been looking for a clean Olympic White Jazzmaster for months.",
      created_at: new Date(now - 1000 * 60 * 60 * 4).toISOString(),
      read: true,
      type: "text",
    },
    {
      id: "msg-11",
      conversation_id: "conv-4",
      sender_id: CURRENT_USER_ID,
      content: "It is all original and includes the case candy. Happy to answer any questions.",
      created_at: new Date(now - 1000 * 60 * 60 * 3).toISOString(),
      read: true,
      type: "text",
    },
    {
      id: "msg-12",
      conversation_id: "conv-4",
      sender_id: "user-4",
      content: "",
      created_at: new Date(now - 1000 * 60 * 50).toISOString(),
      read: false,
      type: "offer",
      offer_id: "offer-2",
    },
    {
      id: "msg-13",
      conversation_id: "conv-4",
      sender_id: "user-4",
      content: "I can do $11,000 cash today if that gets it done.",
      created_at: new Date(now - 1000 * 60 * 48).toISOString(),
      read: false,
      type: "text",
    },
  ],
}
