export type ReviewStatus = "pending" | "approved" | "rejected" | "normalized"

export interface ReviewQueueItem {
  id: string
  submittedValue: string
  aiSuggestion: string | null
  aiConfidence: number
  aiReasoning: string
  attributeId: string
  attributeName: string
  nicheName: string
  submittedByUsername: string
  submittedAt: string
  status: ReviewStatus
  originatingListingId?: string
}

export const mockReviewQueue: ReviewQueueItem[] = [
  {
    id: "rv-001",
    submittedValue: "fndr",
    aiSuggestion: "Fender",
    aiConfidence: 0.94,
    aiReasoning: "Strong phonetic and abbreviation match to 'Fender', a well-known guitar brand. Context: submitted against Brand attribute in Electric Guitars.",
    attributeId: "attr-brand",
    attributeName: "Brand",
    nicheName: "Guitars",
    submittedByUsername: "stratman_66",
    submittedAt: "2026-05-03T14:22:00Z",
    status: "pending",
    originatingListingId: "listing-strat-fndr",
  },
  {
    id: "rv-002",
    submittedValue: "gibosn",
    aiSuggestion: "Gibson",
    aiConfidence: 0.91,
    aiReasoning: "Clear typographical transposition error. 'gibosn' → 'Gibson' with high confidence. Matches existing allowed value.",
    attributeId: "attr-brand",
    attributeName: "Brand",
    nicheName: "Guitars",
    submittedByUsername: "lp_collector",
    submittedAt: "2026-05-03T11:08:00Z",
    status: "pending",
    originatingListingId: "listing-lp-gibosn",
  },
  {
    id: "rv-003",
    submittedValue: "Partscaster Garage Co.",
    aiSuggestion: null,
    aiConfidence: 0.52,
    aiReasoning: "Novel brand name. Appears to be a legitimate small-batch guitar builder. Not a match for any existing allowed value. Manual review recommended to verify legitimacy before adding to shared taxonomy.",
    attributeId: "attr-brand",
    attributeName: "Brand",
    nicheName: "Guitars",
    submittedByUsername: "boutique_gear",
    submittedAt: "2026-05-03T09:45:00Z",
    status: "pending",
    originatingListingId: "listing-partscaster",
  },
  {
    id: "rv-004",
    submittedValue: "fEnDeR",
    aiSuggestion: "Fender",
    aiConfidence: 0.97,
    aiReasoning: "Case normalization. 'fEnDeR' is 'Fender' with non-standard casing. Auto-approval candidate.",
    attributeId: "attr-brand",
    attributeName: "Brand",
    nicheName: "Guitars",
    submittedByUsername: "alt_caps_user",
    submittedAt: "2026-05-02T22:17:00Z",
    status: "pending",
  },
  {
    id: "rv-005",
    submittedValue: "xyz123!!!",
    aiSuggestion: null,
    aiConfidence: 0.04,
    aiReasoning: "No plausible match to any known brand or value. String appears to be test input or spam. Recommend rejection.",
    attributeId: "attr-brand",
    attributeName: "Brand",
    nicheName: "Guitars",
    submittedByUsername: "new_user_44",
    submittedAt: "2026-05-02T19:03:00Z",
    status: "pending",
  },
  {
    id: "rv-006",
    submittedValue: "Shoei Neotec",
    aiSuggestion: "Shoei",
    aiConfidence: 0.78,
    aiReasoning: "'Shoei Neotec' appears to be a brand + model name conflated into the Brand field. 'Shoei' is the brand; 'Neotec' is the model series. Consider splitting or normalizing to 'Shoei'.",
    attributeId: "attr-gear-brand",
    attributeName: "Brand",
    nicheName: "Motorcycles",
    submittedByUsername: "moto_rider_pdx",
    submittedAt: "2026-05-02T16:55:00Z",
    status: "pending",
    originatingListingId: "listing-shoei-neotec",
  },
  {
    id: "rv-007",
    submittedValue: "Two Rock",
    aiSuggestion: null,
    aiConfidence: 0.61,
    aiReasoning: "'Two Rock' is a legitimate boutique amplifier brand. Not currently in the allowed values for Amps & Effects > Brand. Moderate confidence — may be a valid addition to shared taxonomy.",
    attributeId: "attr-amp-brand",
    attributeName: "Brand",
    nicheName: "Guitars",
    submittedByUsername: "tone_chaser_tx",
    submittedAt: "2026-05-02T14:30:00Z",
    status: "pending",
    originatingListingId: "listing-two-rock",
  },
  {
    id: "rv-008",
    submittedValue: "Dumble",
    aiSuggestion: null,
    aiConfidence: 0.83,
    aiReasoning: "'Dumble' refers to Howard Dumble's hand-built amplifiers — a real and highly desirable boutique brand. Not in current allowed values. High-confidence legitimate addition.",
    attributeId: "attr-amp-brand",
    attributeName: "Brand",
    nicheName: "Guitars",
    submittedByUsername: "boutique_amp_guy",
    submittedAt: "2026-05-01T20:11:00Z",
    status: "pending",
    originatingListingId: "listing-dumble-ods",
  },
  {
    id: "rv-009",
    submittedValue: "Aria Pro II",
    aiSuggestion: null,
    aiConfidence: 0.87,
    aiReasoning: "'Aria Pro II' is a real and established Japanese guitar brand. Not in current allowed values. Recommend adding to shared taxonomy.",
    attributeId: "attr-brand",
    attributeName: "Brand",
    nicheName: "Guitars",
    submittedByUsername: "vintage_jp_gear",
    submittedAt: "2026-05-01T11:44:00Z",
    status: "pending",
  },
  {
    id: "rv-010",
    submittedValue: "ARAI",
    aiSuggestion: "Arai",
    aiConfidence: 0.92,
    aiReasoning: "Case normalization. 'ARAI' → 'Arai'. Existing value in allowed values. Merge/normalize candidate.",
    attributeId: "attr-gear-brand",
    attributeName: "Brand",
    nicheName: "Motorcycles",
    submittedByUsername: "helmet_collector",
    submittedAt: "2026-04-30T09:22:00Z",
    status: "pending",
  },
  {
    id: "rv-011",
    submittedValue: "Taylor 814ce",
    aiSuggestion: "Taylor",
    aiConfidence: 0.76,
    aiReasoning: "'Taylor 814ce' appears to combine brand and model in the Brand field. 'Taylor' is the brand; '814ce' is the model. Consider normalizing to 'Taylor' and prompting user to add model to Series/Model field.",
    attributeId: "attr-ac-brand",
    attributeName: "Brand",
    nicheName: "Guitars",
    submittedByUsername: "acoustic_only",
    submittedAt: "2026-04-29T18:05:00Z",
    status: "pending",
    originatingListingId: "listing-taylor-814",
  },
  {
    id: "rv-012",
    submittedValue: "Collings",
    aiSuggestion: null,
    aiConfidence: 0.89,
    aiReasoning: "'Collings' is a well-respected boutique acoustic guitar manufacturer. Not currently in allowed values for Acoustic Guitars > Brand. High-confidence legitimate addition.",
    attributeId: "attr-ac-brand",
    attributeName: "Brand",
    nicheName: "Guitars",
    submittedByUsername: "boutique_acoustic",
    submittedAt: "2026-04-29T10:33:00Z",
    status: "pending",
    originatingListingId: "listing-collings-om2h",
  },
]

export const pendingReviewCount = mockReviewQueue.filter(
  (item) => item.status === "pending",
).length
